package view;

import controller.ClienteDAO;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;



/**
 *
 * @author jhaly
 */
public class TelaCliente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCliente.class.getName());

    /**
     * Creates new form TelaCliente
     */
    public TelaCliente() {
        initComponents();
    }
    public void listar(){
        ClienteDAO dao = new ClienteDAO();
        
        List<Cliente>  lista = dao.listarClientes();
        DefaultTableModel dados = (DefaultTableModel) jTblCliente.getModel();
        dados.setNumRows(0);

        for (Cliente c:lista) {
            dados.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getDocumento(),
                c.getTipoCliente(),
                c.getTelefone(),
                c.getEmail(),
                c.getLogradouro(),
                c.getNumero(),
                c.getComplemento(),
                c.getBairro(),
                c.getCidade(),
                c.getEstado(),
                c.getCep(),
                c.getObservacoes(),
            });

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupBtnTipoCliente = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabelNome = new javax.swing.JLabel();
        jLabelDocumento = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTxtNome = new javax.swing.JTextField();
        jTxtDocumento = new javax.swing.JTextField();
        jTxtTelefone = new javax.swing.JFormattedTextField();
        jLabelTelefone = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jTxtEmail = new javax.swing.JTextField();
        jLabelCep = new javax.swing.JLabel();
        jLabelTelefone2 = new javax.swing.JLabel();
        jLabelTelefone3 = new javax.swing.JLabel();
        jTxtCep = new javax.swing.JFormattedTextField();
        jBtnJuridico = new javax.swing.JRadioButton();
        jBtnFisico = new javax.swing.JRadioButton();
        jTxtNumero = new javax.swing.JTextField();
        jTxtEndereco = new javax.swing.JTextField();
        jLabelCep1 = new javax.swing.JLabel();
        jTxtCidade = new javax.swing.JTextField();
        jLabelTelefone4 = new javax.swing.JLabel();
        jCbxEstado = new javax.swing.JComboBox<>();
        jLabelCep2 = new javax.swing.JLabel();
        jTxtBairro = new javax.swing.JTextField();
        jLabelCep3 = new javax.swing.JLabel();
        jTxtComplemento = new javax.swing.JTextField();
        jBtnAdicionar = new javax.swing.JButton();
        jBtnEditar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnAtualizar = new javax.swing.JButton();
        jLabelCep4 = new javax.swing.JLabel();
        jTxtObs = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblCliente = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImages(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabelNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelNome.setText("Nome:");

        jLabelDocumento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelDocumento.setText("Documento:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Tipo Cliente:");

        jTxtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNomeActionPerformed(evt);
            }
        });

        jTxtDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtDocumentoActionPerformed(evt);
            }
        });

        try {
            jTxtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9-####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelTelefone.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTelefone.setText("Telefone:");

        jLabelEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelEmail.setText("Email:");

        jTxtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEmailActionPerformed(evt);
            }
        });

        jLabelCep.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCep.setText("Cep:");

        jLabelTelefone2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTelefone2.setText("Endereço: ");

        jLabelTelefone3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTelefone3.setText("N:");

        try {
            jTxtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTxtCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCepActionPerformed(evt);
            }
        });
        jTxtCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtCepKeyPressed(evt);
            }
        });

        groupBtnTipoCliente.add(jBtnJuridico);
        jBtnJuridico.setText("Pessoa Júridica");

        groupBtnTipoCliente.add(jBtnFisico);
        jBtnFisico.setText("Pessoa Física");
        jBtnFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFisicoActionPerformed(evt);
            }
        });

        jTxtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNumeroActionPerformed(evt);
            }
        });

        jTxtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEnderecoActionPerformed(evt);
            }
        });

        jLabelCep1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCep1.setText("Cidade:");

        jTxtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCidadeActionPerformed(evt);
            }
        });

        jLabelTelefone4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTelefone4.setText("Estado:");

        jCbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        jLabelCep2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCep2.setText("Bairro:");

        jTxtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtBairroActionPerformed(evt);
            }
        });

        jLabelCep3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCep3.setText("Complemento");

        jTxtComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtComplementoActionPerformed(evt);
            }
        });

        jBtnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-adicionar-50.png"))); // NOI18N
        jBtnAdicionar.setToolTipText("Adiconar Usuário");
        jBtnAdicionar.setMaximumSize(new java.awt.Dimension(80, 80));
        jBtnAdicionar.setMinimumSize(new java.awt.Dimension(80, 80));
        jBtnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAdicionarActionPerformed(evt);
            }
        });

        jBtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-editar-50.png"))); // NOI18N
        jBtnEditar.setToolTipText("Editar Usuário");
        jBtnEditar.setEnabled(false);
        jBtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-excluir-50.png"))); // NOI18N
        jBtnExcluir.setToolTipText("Excluir Usuário");
        jBtnExcluir.setEnabled(false);
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-atualizar-50.png"))); // NOI18N
        jBtnAtualizar.setToolTipText("Excluir Usuário");
        jBtnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAtualizarActionPerformed(evt);
            }
        });

        jLabelCep4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCep4.setText("Obs:");

        jTxtObs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtObsActionPerformed(evt);
            }
        });

        jTblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Documento", "Tipo De Cliente", "Telefone", "E-mail", "Endereço", "Numero", "Complemento", "Bairro", "Cidade", "Eestado", "Cep", "Obs"
            }
        ));
        jTblCliente.setToolTipText("");
        jTblCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTblCliente.setPreferredSize(new java.awt.Dimension(636, 636));
        jTblCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTblCliente);

        jMenu1.setText("Arquivo");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sair");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(471, 471, 471)
                .addComponent(jBtnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnEditar)
                .addGap(18, 18, 18)
                .addComponent(jBtnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnAtualizar)
                .addContainerGap(532, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDocumento)
                            .addComponent(jLabelNome)
                            .addComponent(jLabelTelefone)
                            .addComponent(jLabelCep)
                            .addComponent(jLabelTelefone4)
                            .addComponent(jLabelCep2)
                            .addComponent(jLabelCep4))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelCep3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtComplemento))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTxtCep, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTxtTelefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelEmail)
                                            .addComponent(jLabelTelefone2))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 896, Short.MAX_VALUE)
                                                .addComponent(jLabelTelefone3)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addComponent(jTxtEmail))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelCep1)
                                        .addGap(45, 45, 45)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTxtCidade)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTxtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))))
                            .addComponent(jTxtNome)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtDocumento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnFisico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnJuridico))
                            .addComponent(jTxtObs)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBtnAdicionar, jBtnAtualizar, jBtnEditar, jBtnExcluir});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDocumento)
                    .addComponent(jTxtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jBtnFisico)
                    .addComponent(jBtnJuridico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTelefone)
                    .addComponent(jLabelEmail)
                    .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCep)
                    .addComponent(jTxtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTelefone3)
                    .addComponent(jTxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTelefone2)
                    .addComponent(jTxtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefone4)
                    .addComponent(jCbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCep1)
                    .addComponent(jTxtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCep2)
                    .addComponent(jTxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCep3)
                    .addComponent(jTxtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCep4)
                    .addComponent(jTxtObs, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jBtnAdicionar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnAtualizar, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jBtnEditar, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jBtnExcluir)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBtnAdicionar, jBtnAtualizar, jBtnEditar, jBtnExcluir});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        int op;
        
        op = JOptionPane.showConfirmDialog(null, "Voce deseja sair?");
        
        if (op == 0){
            dispose();
        }
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        int op;
        
        op = JOptionPane.showConfirmDialog(null, "Voce deseja sair?");
        
        if (op == 0){
            dispose();
        }
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jTxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNomeActionPerformed

    private void jTxtDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtDocumentoActionPerformed

    private void jTxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEmailActionPerformed

    private void jTxtCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCepActionPerformed

    private void jBtnFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFisicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnFisicoActionPerformed

    private void jTxtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNumeroActionPerformed

    private void jTxtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEnderecoActionPerformed

    private void jTxtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCidadeActionPerformed

    private void jTxtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtBairroActionPerformed

    private void jTxtComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtComplementoActionPerformed

    private void jBtnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAdicionarActionPerformed
            if (jTxtNome.getText().isEmpty() || jTxtDocumento.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Preencha os campos de Nome e Documento!!!");
            } else {
                String tipoCliente = "";
                if (jBtnFisico.isSelected()){
                    tipoCliente = "Pessoa Física";
                    String nome = jTxtNome.getText();
                    String documento = jTxtDocumento.getText();
                    String telefone = jTxtTelefone.getText();
                    String email = jTxtEmail.getText();
                    String cep = jTxtCep.getText();
                    String logradouro = jTxtEndereco.getText();
                    String numero = jTxtNumero.getText();
                    String estado = jCbxEstado.getSelectedItem().toString();
                    String cidade = jTxtCidade.getText();
                    String bairro = jTxtBairro.getText();
                    String complemento = jTxtComplemento.getText();
                    String observacoes = jTxtObs.getText();

                    Cliente cliente = new Cliente( nome,  documento,  tipoCliente,  telefone,  email,  numero,  complemento,  cidade,  estado,  cep,  observacoes,  logradouro,  bairro);

                    ClienteDAO dao = new ClienteDAO();
                    dao.adicionarCliente(cliente);
                }else {
                    tipoCliente = "Pessoa Jurídica";
                    String nome = jTxtNome.getText();
                    String documento = jTxtDocumento.getText();
                    String telefone = jTxtTelefone.getText();
                    String email = jTxtEmail.getText();
                    String cep = jTxtCep.getText();
                    String logradouro = jTxtEndereco.getText();
                    String numero = jTxtNumero.getText();
                    String estado = jCbxEstado.getSelectedItem().toString();
                    String cidade = jTxtCidade.getText();
                    String bairro = jTxtBairro.getText();
                    String complemento = jTxtComplemento.getText();
                    String observacoes = jTxtObs.getText();

                    Cliente cliente = new Cliente(nome,  documento,  tipoCliente,  telefone,  email,  numero,  complemento,  cidade,  estado,  cep,  observacoes,  logradouro,  bairro);

                    ClienteDAO dao = new ClienteDAO();
                    dao.adicionarCliente(cliente);
                }
       }
    }//GEN-LAST:event_jBtnAdicionarActionPerformed


    private void jBtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditarActionPerformed
        // TODO add your handling code here:
        if ((jTxtNome.getText().isEmpty() || jTxtDocumento.getText().isEmpty())){
                JOptionPane.showMessageDialog(null, "Preencha os campos de Nome e Documento!!!");
        } else {
            String nome = jTxtNome.getText();
            String documento = jTxtDocumento.getText();
            String tipoCliente = "";
            if (jBtnFisico.isSelected()) {
                tipoCliente = "Pessoa Física";
                } else if (jBtnJuridico.isSelected()) {
                    tipoCliente = "Pessoa Jurídica";
                }
            String email = jTxtEmail.getText();
            String telefone = jTxtTelefone.getText();
            String cep = jTxtCep.getText();
            String logradouro = jTxtEndereco.getText();
            String estado = jCbxEstado.getSelectedItem().toString();
            String numero = jTxtNumero.getText();
            String cidade = jTxtCidade.getText();
            String bairro = jTxtBairro.getText();
            String complemento = jTxtComplemento.getText();
            String observacoes = jTxtObs.getText();
            
            int id = (int) jTblCliente.getValueAt(jTblCliente.getSelectedRow(), 0);

            Cliente cliente = new Cliente(nome,  documento,  tipoCliente,  telefone,  email,  numero,  complemento,  cidade,  estado,  cep,  observacoes,  logradouro,  bairro);
            cliente.setId(id);
            ClienteDAO dao = new ClienteDAO();
            dao.alterarCliente(cliente);
            jTxtNome.setText("");
            jTxtDocumento.setText("");
            groupBtnTipoCliente.clearSelection();
            jTxtEmail.setText("");
            jTxtTelefone.setText("");
            jTxtCep.setText("");
            jTxtEndereco.setText("");
            jTxtNumero.setText("");
            jCbxEstado.setSelectedItem("AC");
            jTxtCidade.setText("");
            jTxtBairro.setText("");
            jTxtComplemento.setText("");
            jTxtObs.setText("");
            jBtnAdicionar.setEnabled(true);
            jBtnEditar.setEnabled(false);
            jBtnExcluir.setEnabled(false);
        }
    }//GEN-LAST:event_jBtnEditarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
           // TODO add your handling code here:
           if ((jTxtNome.getText().isEmpty()) || (jTxtDocumento.getText().isEmpty())
           || (jTxtEmail.getText().isBlank()) || (jTxtTelefone.getText().isEmpty())) {
           JOptionPane.showMessageDialog(null, "Preencha todos os campos!!!");
           
           } else {
               int ex = JOptionPane.showConfirmDialog(null, "Realmente deseja excluir esse usuário?");
               if (ex == JOptionPane.YES_OPTION){
               Cliente clientes = new Cliente();
               clientes.setId((int) jTblCliente.getValueAt(jTblCliente.getSelectedRow(), 0));
               ClienteDAO dao = new ClienteDAO();
               dao.excluirCliente(clientes);
               jTxtNome.setText("");
               jTxtDocumento.setText("");
               groupBtnTipoCliente.clearSelection();
               jTxtEmail.setText("");
               jTxtTelefone.setText("");
               jTxtCep.setText("");
               jTxtEndereco.setText("");
               jTxtNumero.setText("");
               jCbxEstado.setSelectedItem("AC");
               jTxtCidade.setText("");
               jTxtBairro.setText("");
               jTxtComplemento.setText("");
               jTxtObs.setText("");
               jBtnAdicionar.setEnabled(true);
               jBtnEditar.setEnabled(false);
               jBtnExcluir.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAtualizarActionPerformed
        // TODO add your handling code here:
        listar();
        jTxtNome.setText("");
        jTxtDocumento.setText("");
        groupBtnTipoCliente.clearSelection();
        jTxtEmail.setText("");
        jTxtTelefone.setText(""); 
        jTxtCep.setText(""); 
        jTxtEndereco.setText("");
        jTxtNumero.setText("");
        jCbxEstado.setSelectedItem("AC");
        jTxtCidade.setText("");
        jTxtBairro.setText("");
        jTxtComplemento.setText("");
        jTxtObs.setText("");
        jBtnAdicionar.setEnabled(true);
        jBtnEditar.setEnabled(false);
        jBtnExcluir.setEnabled(false);
    }//GEN-LAST:event_jBtnAtualizarActionPerformed

    private void jTxtCepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCepKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) { 
         Cliente obj =  new Cliente();
         ClienteDAO dao = new ClienteDAO();
         obj = dao.buscaCep(jTxtCep.getText());
         
         jTxtEndereco.setText(obj.getLogradouro());
         jTxtBairro.setText(obj.getBairro());
         jTxtCidade.setText(obj.getCidade());
         jCbxEstado.setSelectedItem(obj.getEstado());               
         //System.out.println(obj.getEstado());
         
     }
    }//GEN-LAST:event_jTxtCepKeyPressed

    private void jTxtObsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtObsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtObsActionPerformed

    private void jTblClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblClienteMouseClicked

        
        int selectedRow = jTblCliente.getSelectedRow();
        if (selectedRow != -1) {  // só acessa se houver linha selecionada
            jTxtNome.setText(String.valueOf(jTblCliente.getValueAt(selectedRow, 1)));
            jTxtDocumento.setText(String.valueOf(jTblCliente.getValueAt(selectedRow, 2)));
            jTxtTelefone.setText(String.valueOf(jTblCliente.getValueAt(selectedRow, 4)));
            jTxtEmail.setText(String.valueOf(jTblCliente.getValueAt(selectedRow, 5)));
            jTxtEndereco.setText(String.valueOf(jTblCliente.getValueAt(selectedRow, 6)));
            jTxtNumero.setText(String.valueOf(jTblCliente.getValueAt(selectedRow, 7)));
            jTxtComplemento.setText(String.valueOf(jTblCliente.getValueAt(selectedRow, 8)));
            jTxtBairro.setText(String.valueOf(jTblCliente.getValueAt(selectedRow, 9)));
            jTxtCidade.setText(String.valueOf(jTblCliente.getValueAt(selectedRow, 10)));
            jCbxEstado.setSelectedItem(String.valueOf(jTblCliente.getValueAt(selectedRow, 11)));
            jTxtCep.setText(String.valueOf(jTblCliente.getValueAt(selectedRow, 12)));
            jTxtObs.setText(String.valueOf(jTblCliente.getValueAt(selectedRow, 13)));

            String tipo = jTblCliente.getValueAt(selectedRow, 3).toString();
            if (tipo.equals("Pessoa Física")) {
                jBtnFisico.setSelected(true);
            } else {
                jBtnJuridico.setSelected(true);
            }

            jBtnAdicionar.setEnabled(false);
            jBtnEditar.setEnabled(true);
            jBtnExcluir.setEnabled(true);
        }
    }//GEN-LAST:event_jTblClienteMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        listar();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCliente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup groupBtnTipoCliente;
    private javax.swing.JButton jBtnAdicionar;
    private javax.swing.JButton jBtnAtualizar;
    private javax.swing.JButton jBtnEditar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JRadioButton jBtnFisico;
    private javax.swing.JRadioButton jBtnJuridico;
    private javax.swing.JComboBox<String> jCbxEstado;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelCep;
    private javax.swing.JLabel jLabelCep1;
    private javax.swing.JLabel jLabelCep2;
    private javax.swing.JLabel jLabelCep3;
    private javax.swing.JLabel jLabelCep4;
    private javax.swing.JLabel jLabelDocumento;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JLabel jLabelTelefone2;
    private javax.swing.JLabel jLabelTelefone3;
    private javax.swing.JLabel jLabelTelefone4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblCliente;
    private javax.swing.JTextField jTxtBairro;
    private javax.swing.JFormattedTextField jTxtCep;
    private javax.swing.JTextField jTxtCidade;
    private javax.swing.JTextField jTxtComplemento;
    private javax.swing.JTextField jTxtDocumento;
    private javax.swing.JTextField jTxtEmail;
    private javax.swing.JTextField jTxtEndereco;
    private javax.swing.JTextField jTxtNome;
    private javax.swing.JTextField jTxtNumero;
    private javax.swing.JTextField jTxtObs;
    private javax.swing.JFormattedTextField jTxtTelefone;
    // End of variables declaration//GEN-END:variables
}
